- name: Provision VM
  hosts: localhost
  tasks:
    - name: Get VMs list
      community.libvirt.virt:
        command: list_vms
      register: existing_vms
      changed_when: no

    - name: Save VM template
      template:
        src: vm-template.xml.j2
        dest: /tmp/vm-template.xml

    - name: Create VM if not exists
      block:
        - name: Define vm
          #community.libvirt.virt:
          #  command: define
          #  xml: "{{ lookup('template', 'vm-template.xml.j2') }}"
          command: virsh create --file /tmp/vm-template.xml 
      when: "vm_name not in existing_vms.list_vms"

    - name: Ensure VM is started
      community.libvirt.virt:
        name: "{{ vm_name }}"
        state: running
      register: vm_start_results
      until: "vm_start_results is success"
      retries: 15
      delay: 2
